// $Id: printtokens.c,v 1.7 2011-09-22 18:18:42-07 - - $

//
// This program, when linked with a parser generated by bison,
// will print out all of the terminal symbols, both as integers
// and as symbols.
//


#include <stdio.h>
#include <string.h>

const char *get_yytname (int);

int main (void) {
   int token;
   for (token = 0; token <= (1<<10); ++token) {
      const char *name = get_yytname (token);
      if (strcmp (name, "$undefined") == 0) continue;
      (void) printf ("%5d %s\n", token, name);
   };
   return 0;
}

int yylex (void) {
   return 0;
}

void yyerror (char* message) {
   fprintf (stderr, "%s\n", message);
}

